name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: |
        As a security analyst, I want to...
        So that I can...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        The feature should...
        
        Example usage:
        ```bash
        weblog-hunter --new-feature ...
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: I considered using...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New detection signature
        - New report format
        - Performance improvement
        - CLI enhancement
        - API addition
        - Integration with other tools
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Critical for my workflow
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, examples, or links
      placeholder: Screenshots, links to similar features in other tools, etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in implementing this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing once implemented
        - label: I can help with documentation

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and PRs for similar features
          required: true
        - label: This feature aligns with the project's goals
          required: true
